# fly.toml app configuration file generated for md2pdf
# Documentation: https://fly.io/docs/reference/configuration/

app = "md2pdf"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8501"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "60s"
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/_stcore/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

